# Generated by Django 4.1 on 2022-09-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_clone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='feed',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
