# Generated by Django 4.1 on 2022-09-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram_clone", "0005_alter_feed_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
    ]
