# Generated by Django 4.1 on 2022-08-29 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='thumbnail',
            new_name='profile_image',
        ),
    ]
